In [1]:
import imagej
import random
import csv
import tkinter as tk
from tkinter import simpledialog
from tkinter.filedialog import askopenfilename
from tkinter.filedialog import asksaveasfile
import pandas as pd
from tkinter import *
import numpy as np
from pathlib import Path




import os

import csv
import sys
import subprocess
from subprocess import call, PIPE, STDOUT
from collections import defaultdict

In [2]:
#ij = imagej.init('/Applications/Fiji.app')

def open_file(filepath):

    os.system("java -Xmx40000m -jar /Users/spencerlab/Downloads/Fiji.app/jars/ij-1.52n.jar -ijpath /Userspencerlab/Downloads/Fiji.app "+ filepath+ " &")

def call_macro():
    os.system("java -Xmx40000m -jar /Users/spencerlab/Downloads/Fiji.app/jars/ij-1.52n.jar -ijpath /Userspencerlab/Downloads/Fiji.app -macro  /Users/spencerlab/Desktop/final_files/Code/Macro.ijm &")

In [3]:
#stack = askopenfilename()
#file_to_open = "/Users/spencerlab/Desktop/final_files/Day_3/\#1/Stack_day_3.tif"
#file_to_open = stack
#open_file(file_to_open)

In [4]:
#call_macro()

In [6]:
app = tk.Tk()
app.geometry("600x600")
arr2 =[[-5,-5]]
arr3 = []
def var_state1():
    print("Yes: %d" % (var1.get()))
    if [i,1] not in arr2:
        if [i,0] not in arr2:
            arr2.append([i,1])
    else:
        try:
            arr2[arr2.index([i,0])] = [i,1]
        except:
            s=0
    print(arr2)
    a = df.iloc[:,4].values
    for k in range (len(arr2)):
        for j in range (len(arr2[k])):
            if(arr2[k][1]==1):
                a[k]="Y"
            elif(arr2[k][1]==0):
                a[k]="N"
            else:
                a[k]="U"
def var_state2():
    print("No: %d" % (var2.get()))
    if [i,1] not in arr2:
        if [i,0] not in arr2:
            arr2.append([i,0])
    else:
        try:
            print("ran")
            arr2[arr2.index([i,1])] = [i,0]
            #np.where([i,1]) = [i,1]
        except:
            s=0
    print(arr2)
    a = df.iloc[:,4].values
    for k in range (len(arr2)):
        for j in range (len(arr2[k])):
            if(arr2[k][1]==1):
                a[k]="Y"
            elif(arr2[k][1]==0):
                a[k]="N"
            else:
                a[k]="U"
def var_state3():
    print("Unsure: %d" % (var9.get()))
    if [i,1] not in arr2:
        if [i,0] not in arr2:
            arr2.append([i,2])
    else:
        try:
            print("ran2")
            arr2[arr2.index([i,1])] = [i,0]
            #np.where([i,1]) = [i,1]
        except:
            s=0
    print(arr2)
    a = df.iloc[:,4].values
    for k in range (len(arr2)):
        for j in range (len(arr2[k])):
            if(arr2[k][1]==1):
                a[k]="Y"
            elif(arr2[k][1]==0):
                a[k]="N"
            else:
                a[k]="U"
    unsure_window = tk.Tk()
    comment = simpledialog.askstring("Input","Enter message", parent = unsure_window)
    arr3.append([i,comment])
    a = df.iloc[:,17].values
    for k in range(len(arr3)):
        a[arr3[k-1][0]]=arr3[k][1]
def save(): 
    df.rename(columns={'Unnamed: 17':'Comments'},inplace=True)
    a = df.iloc[:,17].values
    for k in range(len(arr3)):
        a[arr3[k][0]]=arr3[k-1][1]
    export = filedialog.asksaveasfilename(defaultextension='.csv')
    df.to_csv(export, index=False, header=True)
def replace_nums(f):
    global i
    if f == 0:
        i = 0
    if f == 1:
        i += 1
    if f == 2:
        i -= 1
    var3.set((str(x[i])))
    var4.set((str(y[i])))
    var5.set((str(z[i])))
    print(type(z[i]))
    print(z[i])
    lmao=int(str(z[i]))
    arr = [int(lmao/3)+1 ,y[i],x[i]]
    
    arr = np.asarray(arr)
    arr3 = arr.reshape([1,3])
    
    data = pd.DataFrame(arr3, columns = ['Z', 'Y', 'X'])
    
    
    
    
    ngc = data.to_csv("/Users/spencerlab/Desktop/final_files/Code/all_green_cells4.csv")
    
    call_macro()
    cmd = ["$HOME/ImageJ/ImageJ -Test.ijm"+" " +var5.get() +" " +var4.get()+" " +var3.get()]
    process = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.STDOUT)
    (stdoutdata, stderrdata) = process.communicate()
    print ('stdoutdata', stdoutdata)
    
def ne_xt():
    global ngc
    global ngc2
    replace_nums(1)
    #ngc = pd.read_csv("/Users/spencerlab/Downloads/all_green_cells4.csv")
    
    
    
    
def start():
    get_dataframe()
    replace_nums(0)
def previous():
    global pgc
    global pgc2
    replace_nums(2)
    #pgc = pd.read_csv("/Users/spencerlab/Downloads/all_green_cells4.csv", mode='a',header=false)
    
def get_dataframe():
    global df
    global col
    global a
    global b
    global arr
    global arr2
    arr2=[]
    global x
    global y
    global z
    stack = askopenfilename()
    file_to_open = stack
    open_file(file_to_open)
    path = Path(stack)
    print(path.name)
    b.set(path.name)
    csv_path = askopenfilename()
    path2 = Path(csv_path)
    print(path2.name)
    a.set(path2.name)
    df = pd.read_csv(csv_path)
    arr = df.to_numpy()
    z = arr[1:,1]
    y = arr[1:,2]
    x = arr[1:,3]

    
tk.Label(app,text="Open ImageJ").grid(row=0,column=0)
b = tk.StringVar()
entry = tk.Entry(app, textvariable=b).grid(row=0, column=1)
tk.Label(app, text='File Path').grid(row=1,column=0)
a = tk.StringVar()
entry = tk.Entry(app, textvariable=a).grid(row=1, column=1)
tk.Button(app, text='Start',command=start).grid(row=2, column=0)

var1 = IntVar(app, value = 1, name = "Yes")
Button(app, text = "Yes", command=var_state1).grid(row=4, column= 0,sticky=W,pady=4)

var2 = IntVar(app, value = 0, name = "No")
Button(app, text = "No", command=var_state2).grid(row=4,column=1, sticky=W,pady=4)

var9 = IntVar(app, value = 2, name = "Unsure")
Button(app, text = "Unsure", command=var_state3).grid(row=4,column=2, sticky=W,pady=4)

Button(app, text = 'Save', command = lambda : save()).grid(row=5,column =1, sticky=W,pady=4)

Button(app, text = "<< Previous", command = previous).grid(row=6,column=1,sticky=W,padx=4,pady=4)
Button(app, text = "Next >>", command = ne_xt).grid(row=6,column=2,sticky=W,padx=4,pady=4)

var6 =StringVar()
l4 = Label(app,text= "X: ").grid(row=7,column=0)
var3 = StringVar()
l1 = Label(app, textvariable = var3).grid(row=7,column=1)

var7 =StringVar()
l4 = Label(app,text= "Y: ").grid(row=8,column=0)
var4 = StringVar()
l2 = Label(app, textvariable = var4).grid(row=8,column=1)

var6 =StringVar()
l4 = Label(app,text= "Z: ").grid(row=9,column=0)
var5 =StringVar()
l3 = Label(app, textvariable = var5).grid(row=9,column=1)


mainloop()

Stack_day_3.tif
all3_JAS (1).csv
<class 'int'>
6
stdoutdata b'/bin/sh: /Users/spencerlab/ImageJ/ImageJ: No such file or directory\n'
<class 'int'>
9
stdoutdata b'/bin/sh: /Users/spencerlab/ImageJ/ImageJ: No such file or directory\n'
<class 'int'>
3
stdoutdata b'/bin/sh: /Users/spencerlab/ImageJ/ImageJ: No such file or directory\n'
<class 'int'>
9
stdoutdata b'/bin/sh: /Users/spencerlab/ImageJ/ImageJ: No such file or directory\n'
<class 'int'>
12
stdoutdata b'/bin/sh: /Users/spencerlab/ImageJ/ImageJ: No such file or directory\n'
<class 'int'>
12
stdoutdata b'/bin/sh: /Users/spencerlab/ImageJ/ImageJ: No such file or directory\n'
<class 'int'>
15
stdoutdata b'/bin/sh: /Users/spencerlab/ImageJ/ImageJ: No such file or directory\n'

In [ ]:
#set slice
#zoom --> set

In [7]:
df

,all3,Z,Y,X,Y/N (1/0),Slice,size,measure,Zb,Yb,Xb,distb,Zt,Yt,Xt,distT,clusterID,Unnamed: 17
0,0,3,1420,1837,Y,2,240,1,1,1831,1418,586.929297,0,1810,1321,646.811410,1,NaN
1,1,6,1415,1850,N,3,273,2,0,1852,1415,616.627927,0,1810,1321,660.228748,1,NaN
2,2,9,1499,1845,U,4,261,3,6,1840,1499,485.804487,0,1881,1625,440.913824,1,green
3,3,3,1522,1868,N,2,81,4,6,1868,1516,493.587885,0,1881,1625,433.519319,1,NaN
4,4,9,1513,1850,N,4,81,5,3,1849,1513,475.921212,0,1881,1625,431.427862,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573,573,534,812,972,Y,179,174,589,533,973,814,225.579254,552,975,809,231.218511,439,NaN
574,574,540,1189,2037,Y,181,375,590,531,2036,1196,1193.637717,693,2030,1198,1197.752479,440,NaN
575,575,543,902,769,Y,182,447,591,543,772,901,185.267374,564,764,891,185.388781,441,NaN
576,576,540,1151,1342,Y,181,123,592,540,1342,1151,270.114790,597,1340,1152,273.989051,442,NaN
577,577,585,1305,799,N,196,78,593,584,798,1306,717.006973,618,800,1306,716.353963,443,NaN

In [54]:
arr3

[]

In [51]:
a = df.iloc[:,17].values
for k in range(len(arr3)):
    a[arr3[k][0]]=arr3[k][1]
a

array(['green', nan, nan, nan, 'green', nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, '2 cells', nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, '2 cells', nan, '3 cells', nan, nan,
       'same as one cell from 187', nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, '2 cells', nan, nan, nan, nan,
       nan, nan, nan, nan, nan, '2 cells', nan, nan, '2 cells', nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       '2 cells', nan, nan, nan, nan, nan, nan, nan, '2 cells', nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan,
       'Center is autofluor but green cell off centered', nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       'No cell in center but there are other cells right nearby within the 30 pixel circle',
       nan, nan, 'Round Cell inside vesssel', nan, nan, nan, nan, nan,
       nan, nan, 'Cell appears inside vessel', nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, '390', '393', '387', '390', '390', '396', '396',
       '402', '402', '405', '402', '405', '405', '405', '408', '408',
       '411', '411', '417', '417', '417', '420', '420', '420', '423',
       '420', '426', '423', '429', '423', '429', '432', '429', '429',
       '429', '429', '432', '438', '432', '432', '432', '435', '435',
       '438', '441', '444', '447', '453', nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan], dtype=object)

In [ ]:
orig=pd.read_csv("/Users/spencerlab/Downloads/all_green_cells4.csv")
saved=pd.read_cssv("some.csv")
saved = saved[:,1]
z=np.colstack()

In [ ]:
call_macro()

In [ ]:


"/Users/spencerlab/Downloads/all_green_cells4.csv"